### ISSUE TITLE
any plan for using local LLM?

### ISSUE THREAD

**Issue by zhanpengjie** [naem1023/LLMCompiler-Pro#3]
great work , wish to kown how to run with local LLM like Qwen or other open llms

**Comment by naem1023** [comment]
Although I initially planned to implement a local LLM using outlines and JSON mode, I wasn’t able to focus on it due to the demands of my work. Currently, we’re utilizing LLM clients through the OpenAI SDK, so if there’s a local LLM SDK available that supports JSON mode in a similar style, we could easily start leveraging a local LLM right away
